import * as Yup from "yup";

export const PdfEccSchema = Yup.object().shape({
  archdiocese: Yup.string().max(200),
  city: Yup.string().max(200),
  parish: Yup.string().max(200),
  hisName: Yup.string().max(200),
  hisNickname: Yup.string().max(200),
  hisBirthdate: Yup.string().max(200),
  hisProfission: Yup.string().max(200),
  hisReligion: Yup.string().max(200),
  herName: Yup.string().max(200),
  herNickname: Yup.string().max(200),
  herBirthdate: Yup.string().max(200),
  herProfission: Yup.string().max(200),
  herReligion: Yup.string().max(200),
  marriageReligious: Yup.bool(),
  whichParish: Yup.string().max(200),
  address: Yup.string().max(200),
  district: Yup.string().max(200),
  cep: Yup.string().max(200),
  cityState: Yup.string().max(200),
  parishAddress: Yup.string().max(200),
  addressNumber: Yup.string().max(200),
  apartmentNumber: Yup.string().max(200),
  phoneNumber: Yup.string().max(200),
  hisProfessionalAddress: Yup.string().max(200),
  hisProfessionalPhoneNumber: Yup.string().max(200),
  dateWedding: Yup.string().max(200),
  herProfessionalAddress: Yup.string().max(200),
  herProfessionalPhoneNumber: Yup.string().max(200),
  numberOfChildren: Yup.string().max(200),
  numberFirstStep: Yup.string().max(200),
  dateFirstStep: Yup.string().max(200),
  localFirstStep: Yup.string().max(200),
  activitiesFirstStage: Yup.string().max(200),
  numberSecondStep: Yup.string().max(200),
  dateSecondStep: Yup.string().max(200),
  localSecondStep: Yup.string().max(200),
  activitiesSecondStage: Yup.string().max(200),
  numberThirdStep: Yup.string().max(200),
  dateThirdStep: Yup.string().max(200),
  localThirdStep: Yup.string().max(200),
  activitiesThirdStage: Yup.string().max(200),
  engagementParish: Yup.string().max(200),
  habilities: Yup.string().max(200),
  createDate: Yup.date(),
});
