version: "3.7"

services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres-register-pdf-api
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=register_pdf_db
    volumes:
      - ./data:/data/postgres
